title: O2Docs
description: Official documentation for O2Do
theme: just-the-docs

url: https://o2do-repository.github.io/O2Doc/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template